export const current_products = [
  {
    id: 1,
    name: "Guess Men's Quartz Red Silicone Strap Black Dial 47mm Watch",
    price: 100,
    originalPrice: 150,
    sale: true,
    countdown: false,
    category: "Watches",
    color: "red",
    size: "47mm",
    stock_quantity: 15,
    images: [{ image_url: "/images/Arrival1.jpg" }],
  },
  {
    id: 2,
    name: "Sporty Blazer Men'S Vintage Plaid Blazer",
    price: 100,
    originalPrice: null,
    sale: false,
    countdown: false,
    category: "Clothing",
    color: "brown",
    size: "medium",
    stock_quantity: 8,
    images: [{ image_url: "/images/Arrival2.jpg" }],
  },
  {
    id: 3,
    name: "Woman Beige HandBag",
    price: 50,
    originalPrice: 75,
    sale: true,
    countdown: false,
    category: "Accessories",
    color: "beige",
    size: "medium",
    stock_quantity: 12,
    images: [{ image_url: "/images/Arrival3.jpg" }],
  },
  {
    id: 4,
    name: "Wireless HeadPhone",
    price: 16,
    originalPrice: 30,
    sale: true,
    countdown: false,
    category: "Electronics",
    color: "black",
    size: "small",
    stock_quantity: 20,
    images: [{ image_url: "/images/Arrival4.jpg" }],
  },
  {
    id: 5,
    name: "Sony Ps5 Dualsense Wireless Controller",
    price: 96,
    originalPrice: null,
    sale: false,
    countdown: false,
    category: "Gaming",
    color: "white",
    size: "standard",
    stock_quantity: 5,
    images: [{ image_url: "/images/Arrival5.jpg" }],
  },
  {
    id: 6,
    name: 'ViewSonic 60.96 Cm (24")FHD IPS Monitor|Super clear IPS Panel |180 Hz',
    price: 526,
    originalPrice: 650,
    sale: true,
    countdown: true,
    category: "Electronics",
    color: "black",
    size: '24"',
    stock_quantity: 3,
    images: [{ image_url: "/images/Arrival7.jpg" }],
  },
  {
    id: 7,
    name: "Sony PlayStation Portal Remote Player for PS5 Console",
    price: 206,
    originalPrice: null,
    sale: false,
    countdown: false,
    category: "Gaming",
    color: "black",
    size: "standard",
    stock_quantity: 0,
    images: [{ image_url: "/images/Arrival6.jpg" }],
  },
  {
    id: 8,
    name: "Nike AirForce 1 Custom Light & Dark Blue Splatter",
    price: 260,
    originalPrice: 300,
    sale: true,
    countdown: false,
    category: "Footwear",
    color: "blue",
    size: "9",
    stock_quantity: 7,
    images: [{ image_url: "/images/AirForce1.webp" }],
  },
]

